version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-gravity-bridge-ui-testnet-private:
    image: cudos-gravity-bridge-ui-testnet-private
    container_name: cudos-gravity-bridge-ui-testnet-private
    build:
      dockerfile: CudosBuilders/docker/gravity-bridge-ui/gravity-bridge-ui.release.dockerfile
      context: ../../../
      args:
        ENV_FILE: "$ENV_FILE"
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - shared-cudos-network
    logging:
      driver: $LOGGING_DRIVER
      options:
        max-size: "128m"
        max-file: "1"