version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-faucet-cli:
    image: cudos-faucet-cli
    container_name: cudos-faucet-cli
    build:
      dockerfile: CudosBuilders/docker/faucet/faucet.dockerfile
      context: ../../../
    restart: unless-stopped
    env_file: "$ENV_FILE"
    ports:
      - "5000:5000"
    networks:
      - shared-cudos-network
    logging:
      driver: $LOGGING_DRIVER
      options:
        max-size: "128m"
        max-file: "1"