version: '3.9'

volumes:
  cudosnodedata:
    driver: local

services:
  cudos-deployer-network-node:
    image: cudos-deployer-network-node
    container_name: $CONTAINER_NAME
    build:
      dockerfile: ./node.dockerfile
      context: .
      args:
        DOCKER_GROUP_ID: "$DOCKER_GROUP_ID"
    restart: unless-stopped
    ports:
      - "$SSH_PORT:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
