version: '3.1'

services:
  cudos-standalone-node:
    image: cudos-standalone-node
    container_name: cudos-standalone-node
    build:
      dockerfile: CudosBuilders/docker/standalone-node/standalone-node.dockerfile
      context: ../../../
    environment:
      - CUDOS_HOME=/usr/cudos/cudos-data
      - MONIKER=cudos-standalone-node
      - CHAIN_ID=cudos-standalone-network
      - ORCH_ETH_ADDRESS=0x0000000000000000000000000000000000000000
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"