version: '3.9'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  debug-node:
    image: $NAME
    container_name: $NAME
    build:
      dockerfile: CudosBuilders/docker/debug-nodes/$DOCKERFILE
      context: ../../../
      args:
        USER_ID: "0"
        USER_NAME: "root"
        GROUP_ID: "0"
        GROUP_NAME: "root"
        CHAIN_ID: "$CHAIN_ID"
    restart: unless-stopped
    environment:
      - CUDOS_HOME=$CUDOS_HOME
      - CHAIN_ID=$CHAIN_ID
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
      - '../../../CudosBuilders:/usr/cudos/CudosBuilders'
      - '../../../CudosNode:/usr/cudos/CudosNode'
      - '../../../CudosHack:/usr/cudos/CudosHack'
      - '../../../CudosGravityBridge:/usr/cudos/CudosGravityBridge'
      - '../../../CudosUtils:/usr/cudos/CudosUtils'
      - '../../../cosmos-sdk:/usr/cudos/cosmos-sdk'
      - '../../../ibc-go:/usr/cudos/ibc-go'
      - '../../../tendermint:/usr/cudos/tendermint'
      - '../../../ethermint:/usr/cudos/ethermint'

    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${EXPOSE_IP}:${PORT26656}:26656"
      - "${EXPOSE_IP}:${PORT26657}:26657"
      - "${EXPOSE_IP}:${PORT1317}:1317"
      - "${EXPOSE_IP}:${PORT9090}:9090"
      - "${EXPOSE_IP}:${PORT26660}:26660"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
