version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  prometeus:
    image: cudos-monitoring-prometeus
    container_name: cudos-monitoring-prometeus
    build:
      dockerfile: ./prometeus.dockerfile
      context: ./
      args:
          PROMETHEUS_CONFIG_PATH_LOCAL: "$PROMETHEUS_CONFIG_PATH_LOCAL"
    restart: unless-stopped
    user: '0:0'
    env_file: "$ENV_FILE"
    volumes:
      - '${PROMETHEUS_DATA_PATH}:/prometheus'
    networks:
      - shared-cudos-network
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    image: cudos-monitoring-graphana
    container_name: cudos-monitoring-graphana
    build:
      dockerfile: ./grafana.dockerfile
      context: ./
    restart: unless-stopped
    user: '0:0'
    volumes:
      - '${GRAFANA_DATA_PATH}:/var/lib/grafana'
    networks:
      - shared-cudos-network
    ports:
      - "${GRAFANA_PORT}:3000"

  exporter:
    image: cudos-monitoring-exporter
    container_name: cudos-monitoring-exporter
    build:
      dockerfile: ./exporter.dockerfile
      context: ./
    restart: unless-stopped
    env_file: "$ENV_FILE"
    networks:
      - shared-cudos-network
    ports:
      - "${EXPORTER_PORT}:9300"