[[chains]]
id = 'vega-testnet'
rpc_addr = 'http://198.50.215.1:46657'
grpc_addr = 'https://198.50.215.1:4090'
websocket_addr = 'ws://198.50.215.1:46657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'uatom' }
gas_adjustment = 1.5
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://13.235.252.154:26657/'
grpc_addr = 'https://juno.stakesystems.io:2083'
websocket_addr = 'ws://13.235.252.154:26657/websocket'
rpc_timeout = '15s'
account_prefix = 'juno'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 10000000
max_msg_num = 10
gas_price = { price = 0.0011, denom = 'uosmo' }
gas_adjustment = 1
clock_drift = '15s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }