version: '3.1'

services:
  cudos-full-node:
    image: cudos-init-full-node
    container_name: $INIT_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/full-node/init-full-node.dockerfile
      context: ../../../
      args:
        USER_ID: "0"
        USER_NAME: "root"
        GROUP_ID: "0"
        GROUP_NAME: "root"
        CUDOS_HOME: "$CUDOS_HOME"
        GENESIS_FILENAME: "$GENESIS_FILENAME"
        SEEDS_FILENAME: "$SEEDS_FILENAME"
        PERSISTENT_PEERS_FILENAME: "$PERSISTENT_PEERS_FILENAME"
        SHOULD_USE_STATE_SYNC: "$SHOULD_USE_STATE_SYNC"
        STATE_SYNC_RPC_SERVERS: "$STATE_SYNC_RPC_SERVERS"
        STATE_SYNC_PEER: "$STATE_SYNC_PEER"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
