version: '3.1'

services:
  cudos-full-node:
    image: cudos-init-full-node
    container_name: $INIT_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/full-node/init-full-node.dockerfile
      context: ../../../
      args:
        CUDOS_HOME: "$CUDOS_HOME"
        GENESIS_FILENAME: "$GENESIS_FILENAME"
        SEEDS_FILENAME: "$SEEDS_FILENAME"
        PERSISTENT_PEERS_FILENAME: "$PERSISTENT_PEERS_FILENAME"
        STATE_SYNC_RPC_SERVERS_FILENAME: "$STATE_SYNC_RPC_SERVERS_FILENAME"
        LOGGING_DRIVER: "$LOGGING_DRIVER"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
