version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

volumes:
  cudosexplorermongodbdata:
    driver: local

services:
  cudos-explorer:
    image: cudos-explorer
    container_name: cudos-explorer
    build:
      dockerfile: CudosBuilders/docker/explorer/explorer.dockerfile
      context: ../../../
      args:
        GENESIS_TIME: "$GENESIS_TIME"
        FAUCET_URL: "$FAUCET_URL"
        INTERNAL_RPC_URL: "$INTERNAL_RPC_URL"
        INTERNAL_API_URL: "$INTERNAL_API_URL"
        EXTERNAL_RPC_URL: "$EXTERNAL_RPC_URL"
        EXTERNAL_API_URL: "$EXTERNAL_API_URL"
        CHAIN_NAME: "$CHAIN_NAME"
        CHAIN_ID: "$CHAIN_ID"
    restart: unless-stopped
    env_file: "$ENV_FILE"
    ports:
      - "3000:3000"
    networks:
      - shared-cudos-network
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on:
      - cudos-explorer-mongodb

  cudos-explorer-mongodb:
    image: 'mongo:latest'
    container_name: cudos-explorer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cudos-root-db-pass
    volumes:
      - 'cudosexplorermongodbdata:/data/db'
      - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    networks:
      - shared-cudos-network
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"