version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-sentry-node:
    image: cudos-start-sentry-node
    container_name: $START_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/sentry-node/start-sentry-node.dockerfile
      context: ../../../
      args:
        CUDOS_HOME: "$CUDOS_HOME"
    restart: unless-stopped
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
    ports:
      - "${PORT26656}:26656"
      - "${PORT26657}:26657"
      - "${PORT1317}:1317"
      - "${PORT9090}:9090"
      - "${PORT26660}:26660"
    networks:
      - shared-cudos-network
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"