version: '3.1'

services:
  node-builder:
    image: node-builder
    container_name: node-builder
    build:
      dockerfile: CudosBuilders/docker/node-builder/node-builder.dockerfile
      context: ../../../
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"