version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  osmosis-testnet-node:
    image: osmosis-testnet-node
    container_name: osmosis-testnet-node-cudos
    build:
      dockerfile: CudosBuilders/docker/osmosis-testnet-node/osmosis-testnet-node.dockerfile
      context: ../../../
      args:
        USER_ID: "0"
        USER_NAME: "root"
        GROUP_ID: "0"
        GROUP_NAME: "root"
        OSMOSIS_HOME: "$OSMOSIS_HOME"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/data-osmosis-testnet-node:$OSMOSIS_HOME'
      - '${SNAPSHOT_URL}:/mnt/snapshot'
    networks:
      - shared-cudos-network