version: '3'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  ethereum-light:
    container_name: ethereum-light
    build:
      context: .
      dockerfile: ./ethereum-light.dockerfile
    ports:
      - "8545:8545"
    networks:
      - shared-cudos-network