version: '3'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  ethereum:
    container_name: ethereum
    build:
      context: .
      dockerfile: ./ethereum-full.dockerfile
      args:
        USER_ID: "0"
        USER_NAME: "root"
        GROUP_ID: "0"
        GROUP_NAME: "root"
    restart: unless-stopped
    ports:
      - "8545:8545"
    volumes:
      - '../../../CudosData/ethereum:/var/ethereum'
    networks:
      - shared-cudos-network
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"