version: '3'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  ethereum-light:
    container_name: ethereum-light
    build:
      context: .
      dockerfile: ./ethereum-light.dockerfile
    restart: unless-stopped
    ports:
      - "8545:8545"
    volumes:
      - '../../../CudosData/ethereum-light:/var/ethereum-light'
    networks:
      - shared-cudos-network