version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-orchestrator:
    image: cudos-orchestrator-debug
    container_name: "$CONTAINER_NAME-debug"
    build:
      dockerfile: CudosBuilders/docker/orchestrator/orchestrator.debug.dockerfile
      context: ../../../
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosGravityBridge/orchestrator:/usr/src'
      - '/usr/src/target'
    networks:
      - shared-cudos-network