version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-orchestrator:
    image: cudos-orchestrator-release
    container_name: "$CONTAINER_NAME-release"
    build:
      dockerfile: CudosBuilders/docker/orchestrator/orchestrator.release.dockerfile
      context: ../../../
    env_file: "$ENV_FILE"
    networks:
      - shared-cudos-network