export GRAVITY_ADDRESS_PREFIX=$ADDRESS_PREFIX
export GRAVITY_FEES=$FEES
export GRAVITY_GRPC=$GRPC
export GRAVITY_ETHRPC=$ETHRPC
export GRAVITY_CONTRACT_ADDR=$CONTRACT_ADDR
export GRAVITY_ETH_PRIV_KEY_HEX=$ETH_PRIV_KEY_HEX
export GRAVITY_COSMOS_ORCH_MNEMONIC=$COSMOS_ORCH_MNEMONIC

./gbt orchestrator