version: '3.1'

services:
  cudos-root-node:
    image: cudos-init-root-node
    container_name: $INIT_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/root-node/init-root-node.dockerfile
      context: ../../../
      args:
        CUDOS_HOME: "$CUDOS_HOME"
        LOGGING_DRIVER: "$LOGGING_DRIVER"
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
