version: '3.1'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-root-node:
    image: cudos-start-root-node
    container_name: $START_CONTAINER_NAME
    build:
      dockerfile: CudosBuilders/docker/root-node/start-root-node.dockerfile
      context: ../../../
      args:
        CUDOS_HOME: "$CUDOS_HOME"
        LOGGING_DRIVER: "$LOGGING_DRIVER"
    restart: unless-stopped
    env_file: "$ENV_FILE"
    volumes:
      - '../../../CudosData/$VOLUME_NAME:$CUDOS_HOME'
    ports:
      - "${EXPOSE_IP}:${PORT26656}:26656"
      - "${EXPOSE_IP}:${PORT26660}:26660"
    networks:
      - shared-cudos-network
    logging:
      driver: "$LOGGING_DRIVER"
      options:
        max-size: "128m"
        max-file: "1"
