[global]
log_level = 'info'

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = ''
rpc_addr = 'http://cudos-start-root-node-1:26657'
grpc_addr = 'http://cudos-start-root-node-1:9090'
websocket_addr = 'ws://cudos-start-root-node-1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cudos'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 1000, denom = 'acudos' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = ''
rpc_addr = 'http://cudos-start-root-node-2:26657'
grpc_addr = 'http://cudos-start-root-node-2:9090'
websocket_addr = 'ws://cudos-start-root-node-2:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cudos'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 1000, denom = 'acudos' }
gas_adjustment = 0.1
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
