version: '3.9'

networks:
  shared-cudos-network:
    name: shared-cudos-network

services:
  cudos-hermes-ibc-relayer:
    image: hermes-ibc-relayer
    container_name: hermes-ibc-relayer
    build:
      dockerfile: CudosBuilders/docker/hermes-ibc-relayer/hermes-ibc-relayer.dev.dockerfile
      context: ../../../
      args:
        USER_ID: "0"
        USER_NAME: "root"
        GROUP_ID: "0"
        GROUP_NAME: "root"
    env_file: "$ENV_FILE"
    volumes:
      - './:/usr/local/src/hermes'
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
